# Generated by Django 5.2.3 on 2025-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='show_address_in_footer',
            new_name='require_email_verification',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_approve_users',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_email_in_header',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_footer',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_phone_in_header',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Recommended size: 200x50 pixels', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2024 Casino Site. All rights reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended size: 32x32 pixels', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Casino Site', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table=None,
        ),
    ]
