# Generated by Django 5.0.6 on 2025-07-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Casino Admin', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
